version: '3'
services:
    web:
        build: .
        command: rerun --background 'ruby portal.rb'
        ports:
            - "8000:8000"
        volumes:
            - ".:/app"
        env_file:
            - ".env"